_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 11
DATASETS:
  TRAIN: ('visdrone_train_base',)
  TEST: ('visdrone_val_base',)
SOLVER:
  IMS_PER_BATCH: 5
  STEPS: (12000, 16000)
  MAX_ITER: 18000
  

OUTPUT_DIR: "checkpoints/visdrone/faster_rcnn/faster_rcnn_R_50_FPN_base"
