_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/visdrone/faster_rcnn/faster_rcnn_R_50_FPN_base/model_reset_remove.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 4
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('visdrone_train_novel_1shot',)
  TEST: ('visdrone_val_novel',)
SOLVER:
  IMS_PER_BATCH: 5
  BASE_LR: 0.01
  STEPS: (10000,)
  MAX_ITER: 1500
  CHECKPOINT_PERIOD: 500
  WARMUP_ITERS: 0
OUTPUT_DIR: "checkpoints/visdrone/faster_rcnn/faster_rcnn_R_50_FPN_ft_novel_1shot"